### ISSUE TITLE
The performance

### ISSUE THREAD

**Issue by zorrocai** [carrierlxk/py-DSLT#2]
Thanks for your good work. I try to run your work following the instructions in Readme. However, the details about Tracking is not clear enough. And I run the run_SiamFC.py in Tracking folder, unfortunately got worse results than original SiamFC. Is there any details that I have missed?

**Comment by carrierlxk** [comment]
Please pay attention to the environment settings. Python 3.6 would degrade the performance significantly.

**Comment by zorrocai** [comment]
Thanks for the quick response.  I noticed the python version.  Python 2.7.12 and pytorch 0.4.0 are installed in my anaconda environment.  I think the decrease may caused by others.

**Comment by carrierlxk** [comment]
The performance of different epoches vary significantly, so pls evaluate more epoches.
